Algoritmo "Exercicio2"

// Disciplina: Algoritmos
// Professor: Hélida
// Descrição: Descreva o que o algoritmo faz
// Autor(a): Lídia Yoko Panza Saito Serrão
// Data: 03/08/2026

// Ler o nome de um usuário e exibir uma mensagem de boas vindas
// Sempre que possivel, olhe a documentação.
Var
  // Seção de Declarações das variáveis
  nome : caractere

Inicio
  // Seção de Comandos

  escreval("Digite seu nome:")
  leia(nome)
  escreval("Olá ",nome,", seja bem-vinda ao Iteam!")


fimalgoritmo