Algoritmo "Exercicio5"

// Disciplina: Algoritmos
// Professor: Hélida
// Descrição: Descreva o que o algoritmo faz
// Autor(a): Lídia Yoko Panza Saito Serrão
// Data: 03/08/2026

// Ler um número e mostrar se é positivo ou negativo
Var
  // Seção de Declarações das variáveis
  numero : inteiro

Inicio
  // Seção de Comandos
  escreval("Digite um número:")
  leia(numero)
  escreval(numero)

  se numero > 0 entao
    escreva("O número é positivo.")

  senao
    escreva("O número é negativo.")
  fimse


fimalgoritmo