Algoritmo "OperadoresA3"

// Disciplina: Algoritmos
// Professor: Hélida
// Descrição: Descreva o que o algoritmo faz
// Autor(a): Lídia Yoko Panza Saito Serrão
// Data: 03/08/2026

//Crie um algoritmo que leia duas notas e calcule a média aritmética

Var
  // Seção de Declarações das variáveis
  nota1, nota2, media : inteiro

Inicio
  // Seção de Comandos

  escreval("Digite a primeira nota: ")
  leia(nota1)
  escreval(nota1)

  escreval("Digite a segunda nota: ")
  leia(nota2)
  escreval(nota2)

  media <- (nota1 + nota2) / 2
  escreval("A média aritmética é: ", media)

fimalgoritmo