Algoritmo "Ex01OperadoresA"

// Disciplina: Algoritmos
// Professor: Helida
// Descricao: Descreva o que o algoritmo faz
// Autor(a): Lidia Yoko Panza Saito Serrao
// Data: 03/08/2026

// Crie um algoritmo que leia um numero inteiro e exiba o seu dobro e o seu triplo

Var
// Sessao de Declaracoes das variaveis
  
  num1, dobro, triplo : inteiro

Inicio
// Sessao de Comandos
  
  escreva("Digite um número: ")
  leia(num1)

  dobro <- num1 * 2  // dobro recebe num1(número digitado pelo usuário) multiplicado por 2
  escreval("O dobro dele é: ", dobro)

  triplo <- num1 * 3
  escreval("O triplo dele é: ", triplo)

fimalgoritmo