Algoritmo "Ex080peradoresA"

// Disciplina: Algoritmos
// Professor: Helida
// Descricao: Descreva o que o algoritmo faz
// Autor (a) : Lidia Yoko Panza Saito Serrao
// Data: 03/08/2026

// Leia a temperatura em graus Celsius e converta para Fahrenheit(F = (C × 9 / 5) + 32)

Var
// Sessao de Declaracoes das variaveis

  c, f: real

inicio
// Sessao de Comandos

   escreva("Digite a temperatura em graus Celsius: ")
   leia(c)

   f <- (c * 9 / 5) + 32

   escreval("A temperatura em Fahrenheit é: ", f)

fimalgoritmo