Algoritmo "Ex060peradoresA"

// Disciplina: Algoritmos
// Professor: Helida
// Descricao: Descreva o que o algoritmo faz
// Autor (a) : Lidia Yoko Panza Saito Serrao
// Data: 03/08/2026

// Calcule o consumo de combustivel de um carro (consumo = distancia / litros)

Var
// Sessao de Declaracoes das variaveis

   consumo, distancia, litros : real

Inicio
// Sessao de Comandos

   escreva("Digite a distancia percorrida (km): ")
   leia (distancia)

   escreva("Digite a quantidade de combustivel gasto (litros): ")
   leia (litros)

   consumo <- distancia / litros

   escreva("O consumo do carro foi de ", consumo, " km/1")

fimalgoritmo