Algoritmo "Exercicio3"

// Disciplina: Algoritmos
// Professor: Hélida
// Descrição: Descreva o que o algoritmo faz
// Autor(a): Lídia Yoko Panza Saito Serrão
// Data: 03/08/2026

// Ler um número do usuário e exibir o dobro
// <- (recebe)
Var
  // Seção de Declarações das variáveis
  num1, dobro: inteiro

Inicio
  // Seção de Comandos

  escreval("Digite um número: ")
  leia(num1)

  dobro <- num1*2
  escreval(num1)
  escreval("O dobro é: ", dobro)

fimalgoritmo