Algoritmo "Ex04"

// Disciplina: Algoritmos
// Professor: Hélida
// Descrição: Descreva o que o algoritmo faz
// Autor(a): Lídia Yoko Panza Saito Serrão
// Data: 06/08/2026

// Leia um número N digitado pelo usuário e imprima de 1 até N, de dois em dois
Var
  // Seção de Declarações das variáveis

  N, i : inteiro

Inicio
  // Seção de Comandos

  N <- 0

  escreval("Digite um número: ")
  leia(N)

  para i de 1 ate N passo 2 faca // lendo número de 2 em 2 até o número digitado pelo usuário
  escreval(i)
fimpara

fimalgoritmo